feat: can retry file upload failure when offline
supabase/storage-dart pull request #44
Opened 2022-11-13 14:56 UTC by dshukertjr

## What kind of change does this PR introduce?

Uploading large files on a spotty connection could be tough. 

- Support [Resumable uploads](https://cloud.google.com/storage/docs/resumable-uploads)
- Retry failed requests

Resumable uploads is not yet supported on Supabase, but we can easily implement retries. This PR adds a retry logic to file uploads in a exponentially backing off manner like the following:

1. 400 ms +/- 25%
2. 800 ms +/- 25%
3. 1,600 ms +/- 25%
4. 3,200 ms +/- 25%
5. 6,400 ms +/- 25%
6. 12,800 ms +/- 25%
7. 25,600 ms +/- 25%
8. and beyond 30,000 ms +/- 25%

By default, the max attempts is set to 25, which should be roughly 10 minutes. 10 minutes was the default time set for Firebase storage. Users can change the retry count like the following. Not sure if this API would provide the best developer experience, so would love to hear comments/ suggestions about anything regarding this PR!
```dart
final uploadTask =
    client.from('public').upload('a.txt', file, maxAttempts: 8);
```

## What is the current behavior?

If a file upload fails, it does no retry, which makes is hard to upload large files over a spotty network connection.

## What is the new behavior?

File upload is automatically retried on SocketException or TimeoutException. 

## Additional context

This feature is not supported on JS client, but there was an feedback from customers handling large files. After some internal discussions, we thought it would make make sense to add this feature to the Flutter SDK.

2022-11-13 15:18 UTC, Vinzent03 requested changes
Am I Right that when I have no internet the method completes 10 mins after start with default configuration?
In addition I would make the max attempt count a config in the storage client as well so you don't have to specify it always.

2022-11-13 15:18 UTC, Vinzent03 commented on a.txt
> +File content
Remove this file

2022-11-13 15:18 UTC, Vinzent03 commented on lib/src/fetch.dart
> +        'POST', url, data, fileOptions, options, maxAttempts);
I would format this the same as the other methods by adding a comma at the end.

2022-11-13 15:18 UTC, Vinzent03 commented on lib/src/fetch.dart
> +        'PUT', url, data, fileOptions, options, maxAttempts);
Maybe format here as well.

2022-11-13 15:18 UTC, Vinzent03 commented on lib/src/storage_file_api.dart
> +        options: FetchOptions(headers: headers), maxAttempts: maxAttempts);
I would format this differently here as well.

2022-11-13 15:18 UTC, Vinzent03 commented on test/basic_test.dart
> +  group('Retry', () {
Two groups with the same name and this group is a duplication of the group 2 groups below, isn't it?

2022-11-14 06:22 UTC, dshukertjr commented on lib/src/fetch.dart
> +        'POST', url, data, fileOptions, options, maxAttempts);
Added a trailing comma here!

2022-11-14 06:22 UTC, dshukertjr commented on lib/src/fetch.dart
> +        'PUT', url, data, fileOptions, options, maxAttempts);
Added a trailing comma here as well.

2022-11-14 06:22 UTC, dshukertjr commented on lib/src/storage_file_api.dart
> +        options: FetchOptions(headers: headers), maxAttempts: maxAttempts);
And another comma here!

2022-11-14 06:25 UTC, dshukertjr commented on test/basic_test.dart
> +  group('Retry', () {
You're right! Deleted the first one!

2022-11-14 06:35 UTC, dshukertjr commented
>Am I Right that when I have no internet the method completes 10 mins after start with default configuration?
In addition I would make the max attempt count a config in the storage client as well so you don't have to specify it always.

Yup, that is correct. It might be a problem for some applications that are already using the library huh? I will update the default max attempts to 1. 

Also, yeah let me update the code so that the user can just define the maxAttempts value when initializing the client so that they don't have to update it every single time. Do you think we should leave the option to override it in each individual functions though?

2022-11-14 06:54 UTC, Vinzent03 commented
Yeah I think setting the default to 1 is better.
I would keep the setting per call so that you can specify a default max attempts in the client, but can change that per call. 

Also, is there any way to stop the retrying? For example if the user wants to abort the upload?

2022-11-14 07:29 UTC, dshukertjr commented
>Also, is there any way to stop the retrying? For example if the user wants to abort the upload?

Aborting the upload is a great point. I wonder how we can do it elegantly.

2022-11-14 07:54 UTC, Vinzent03 commented
Is that even possible? https://github.com/dart-lang/http/issues/424 I think we can ignore the future, but not actually abort the request.

2022-11-14 08:38 UTC, dshukertjr commented
@Vinzent03 
I have updated the code! What do you think about the implementation?

```dart
final abortController = StorageAbortController();

await client.from('public').upload(
      path,
      file,
      abortController: abortController,
    );

...
// Some where else:
abortController.abort();
```

2022-11-14 11:01 UTC, Vinzent03 commented
Suggested edit:
```diff
diff --git a/test/basic_test.dart b/test/basic_test.dart
index 1d984e7..ac85174 100644
--- a/test/basic_test.dart
+++ b/test/basic_test.dart
@@ -331,7 +331,7 @@ void main() {
       expect(response.endsWith('/a.txt'), isTrue);
     });
 
-    test('aborting upload shoudl throw', () async {
+    test('aborting upload should throw', () async {
       final file = File('a.txt');
       file.writeAsStringSync('File content');
 

```

2022-11-14 11:07 UTC, Vinzent03 reviewed
Looks great! Do want to additionally cancel the future as stated [here](https://stackoverflow.com/a/54905898)?

2022-11-14 11:07 UTC, Vinzent03 commented on test/basic_test.dart
> +    test('aborting upload shoudl throw', () async {
typo

2022-11-14 13:00 UTC, bdlukaa requested changes

2022-11-14 13:00 UTC, bdlukaa commented on lib/src/storage_client.dart
> +    int maxAttempts = 1,
I'd rename this to `retryAttempts`. IMO, `maxAttempts` doesn't really provide info about what's being attempted to

2022-11-14 13:00 UTC, bdlukaa commented on lib/src/storage_client.dart
> +          'maxAttempts has to be great than or equal to 1',
What if the dev doesn't want to retry it anytime?

2022-11-14 13:00 UTC, bdlukaa commented on lib/src/types.dart
> +  bool get aborted => _aborted;
Just some docs

```suggestion
  /// Whether the retry operation is aborted
  bool get aborted => _aborted;
```

2022-11-14 14:25 UTC, dshukertjr commented on lib/src/storage_client.dart
> +    int maxAttempts = 1,
Thanks for the suggestion! I did go back and forth between `retryAttempts` and `maxAttempts` as well thinking which one will be better, so really appreciate the suggestion!

If we go with `retryAttempts`, then `retryAttempts = 0` would mean that it would try to upload it once, and will not retry, right? In other words, `retryAttempts = 0` and `maxAttempts = 1` would be the same thing?

2022-11-14 16:05 UTC, Vinzent03 commented
> creating a separate configuration method might provide better developer experience?

I definitely think so.

2022-11-15 01:40 UTC, dshukertjr reviewed
@Vinzent03 
>I definitely think so.

Let's do this!

>One issue with cancelling the future could be though that, as far as understand this, the actual request is no cancelled so that the file may still get uploaded after abort. This should not be the case, so the abort should just stop the retrying.

With the current state, there will not be any more retry attempts once the user calls `abortController.abort()`. I tried to include `CancelableOperation` in the code, but I feel like it might not solve any issues on top of what is already implemented, so I ended up just leaving the code as is, but what do you think?

2022-11-15 01:40 UTC, dshukertjr commented on lib/src/storage_client.dart
> +    int maxAttempts = 1,
Updated to `retryAttempts`!

2022-11-15 09:38 UTC, Vinzent03 commented
Yeah I changed my mind and I think just aborting the retry is better than ignoring the result of the future. The dev can still do the same on the end result future. But we need to document that, because even after abort the request could go on for a long time until it finishes or fails.

Maybe `abort` is not the best name for this, because it doesn't really abort anything, but rather prevent/stop a new retry. What do you think?

2022-11-15 15:55 UTC, dshukertjr commented
>Maybe abort is not the best name for this, because it doesn't really abort anything, but rather prevent/stop a new retry. What do you think?

Agree. Let's rename it. What do you think about the following rename?

```dart
final retryController = StorageRetryController();

await client.from('public').upload(
      path,
      file,
      retryController: retryController,
    );

...
// Some where else:
retryController.cancel();
```

2022-11-15 16:00 UTC, Vinzent03 commented
That's great. Let's use these names.

2022-11-16 08:15 UTC, Vinzent03 commented
Looks great, but what about the config method to change the retry attempts count?

2022-11-16 09:12 UTC, dshukertjr commented
@Vinzent03 
Yeah, I was thinking about that one. What would the use case be when someone wants to change the retry settings after initialization? I could not think of any, so wanted to ask.

2022-11-16 09:41 UTC, Vinzent03 commented
Good question, I can't think of one currently. I just like offering the dev all freedom, when it's not complicated to implement it. I'm fine with leaving as it is as well.

2022-11-16 09:50 UTC, Vinzent03 approved these changes

2022-11-16 12:38 UTC, dshukertjr commented
@Vinzent03 
I agree that giving freedom is good, but at the same time, I don't want to confute people with different options that they might not need. I'd say let's ship this feature, and if such use case emerges, we can add the feature to update the config!

2022-11-16 18:08 UTC, bdlukaa approved these changes

2022-11-17 01:43 UTC, merged