feat: image transform support
supabase/storage-dart pull request #46
Opened 2022-12-02 08:33 UTC by dshukertjr

## What kind of change does this PR introduce?

New image transformation feature will be added to Supabase. This PR adds support for that feature. 

- `transform` option has been added to `getPublicUrl` and `createSignedUrl` methods.
- `download` method has been deprecated in favor of `publicDownload` and `authenticatedDownload` methods.

supabase-js code here
https://github.com/supabase/storage-js/pull/129

## What is the current behavior?

Image transform is not supported

## What is the new behavior?

Image transform feature is supported where images stored on Supabase storage can be resized on the fly.

## We will hold off on merging this until [this](https://github.com/supabase/storage-js/pull/129) PR is merged on storage-js.

2022-12-06 07:26 UTC, Vinzent03 requested changes

2022-12-06 07:26 UTC, Vinzent03 commented on lib/src/storage_file_api.dart
> +    if (transform?.width != null) {
Can't you use `transform.toMap()` here?

2022-12-06 07:26 UTC, Vinzent03 commented on lib/src/types.dart
> +  Map<String, dynamic> toMap() {
I would rename it to `toJson`, because that's the standard and useed by `jsonEncode` as well.

2022-12-06 08:01 UTC, dshukertjr commented on lib/src/types.dart
> +extension ToQueryParams on TransformOptions {
I converted the `toMap` to an extension method so that we can hide it from our users accessing the method.

2022-12-06 08:01 UTC, dshukertjr commented on lib/src/storage_file_api.dart
> +    if (transform?.width != null) {
Great point! Have updated the code!

2022-12-06 08:36 UTC, Vinzent03 commented on lib/src/storage_file_api.dart
> +    if (queryParams.isNotEmpty) {
Can't you remove `queryParams` and use `transformationQuery` directly? `queryParams` isn't used elsewhere.

2022-12-06 08:40 UTC, dshukertjr commented on lib/src/storage_file_api.dart
> +    if (queryParams.isNotEmpty) {
Should be done!

2022-12-06 08:49 UTC, Vinzent03 commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
What about some documentation about these options? Or should they only be documented on the supabase docs website?

2022-12-06 08:51 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
No, you're right. Let me add more documentations around these types and more.

2022-12-06 08:56 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
@Vinzent03 I also wonder if `TransformCrop` is a good name... Which one do you think is the best?
- TransformCrop
- CropOption
- CropType
- TransformOption
or other?

2022-12-06 09:01 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
I personally kind of like `CropOption` now that I see a few options like this.

2022-12-06 09:19 UTC, Vinzent03 commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
I think I like `CropType` or `CropMethod` more. I took a look at the js implementation in https://github.com/supabase/storage-js/pull/129. They have different `resize` types. Is that correct?

2022-12-06 09:19 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
Done!

2022-12-06 09:26 UTC, Vinzent03 commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
Where did the previous resize modes come from? We should include them in a test. At least that the server doesn't throw an error on a may wrong resize mode?

2022-12-06 09:36 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
@Vinzent03 
Yeah, sorry for confusing you with the different resize modes. I was originally looking at [this](https://github.com/supabase/storage-js/pull/128) PR, but then with [this](https://github.com/supabase/storage-js/pull/130) PR, the list of available resize modes changed, and I just changed it right now. 

`cover`, `contain`, and `fill` should be the available resize options as of now, but let's not merge this one until they merge their PR on [supabase-js](https://github.com/supabase/storage-js/pull/129) side.

2022-12-06 12:05 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
Just chatted with the storage team and confirmed that `cover`, `contain`, and `fill` are the finalized resize modes.

2022-12-06 13:31 UTC, bdlukaa requested changes

2022-12-06 13:31 UTC, bdlukaa commented on lib/src/types.dart
> +  TransformOptions({
```suggestion
  const TransformOptions({
```

2022-12-07 12:54 UTC, Vinzent03 commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
Okay great. I really like the documentation of [BoxFit](https://api.flutter.dev/flutter/painting/BoxFit.html) in Flutter. Do you think we can do the same for the resize modes? Or do you think that's overkill.

2022-12-08 02:45 UTC, bdlukaa approved these changes

2022-12-11 03:15 UTC, dshukertjr commented
Just an FYI, but there will most likely be some last minute API change on the storage-js side. Specifically, we might not deprecate `download()` method, and just keep on using it instead of introducing `publicDownload()` and `authenticatedDownload()`. I will reflect those changes once they are confirmed and merged into storage-js library!

2022-12-11 17:39 UTC, Vinzent03 commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
@dshukertjr In case you missed the above message.

2022-12-12 00:47 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
@Vinzent03 Thanks for pinging me! Yeah, that is a great idea! Let me add something similar!

2022-12-12 07:55 UTC, dshukertjr commented on lib/src/types.dart
> +enum TransformCrop { fill, fit, fillDown, force, auto }
Actually, it might be a bit time consuming, so let's come back to that nice idea after launch week!

2022-12-12 17:55 UTC, Vinzent03 requested changes

2022-12-12 17:55 UTC, Vinzent03 commented on lib/src/storage_file_api.dart
> +        if (transform != null) ...{'transform': transform.toQueryParams},
```suggestion
        if (transform != null) 'transform': transform.toQueryParams,
```

2022-12-12 18:10 UTC, dshukertjr commented
We will release a new version of storage-dart tomorrow. Will update the change logs and stuff so that we can release this version right after merging this PR!

2022-12-13 06:40 UTC, merged