url of api
supabase/storage-dart pull request #53
Opened 2023-03-23 17:24 UTC by Ben1980

the URL of the API was not returned within the signedURL

## What kind of change does this PR introduce?

Fixing supabase/supabase-flutter#411

## What is the current behavior?

unlike createSignedUrl, createSignedUrls does not return a URL. It is missing the API URL

## What is the new behavior?

The URL string has been added

2023-03-23 19:52 UTC, Vinzent03 requested changes

2023-03-23 19:52 UTC, Vinzent03 commented on lib/src/storage_file_api.dart
> +        signedUrl: '$url/${e['signedURL']}',
You have one `/` too much here. `sigendURL` already contains a `/`.

2023-03-24 05:15 UTC, Ben1980 commented on lib/src/storage_file_api.dart
> +        signedUrl: '$url/${e['signedURL']}',
Thanks, just corrected it

2023-03-24 12:54 UTC, Vinzent03 approved these changes
Thanks for the fix! LGTM!

2023-03-24 12:55 UTC, merged